export const REACTOR_MODELS = {
  x2: {
    slug: "x2",
    name: "X2",
    category: "Streaming Video Editing",
    description: "Real-time streaming video-to-video editing.",
    price: "$6/HOUR",
    credits: "17 CREDITS/SEC",
    family: "camera",
    docs: "https://docs.reactor.inc/model-api-reference/x2/overview",
    prompt: "Replace the person with a cinematic silver robot",
    presets: ["Replace with reference", "Spawn at pointer", "Follow the drag"],
  },
  "happy-oyster": {
    slug: "happy-oyster",
    name: "Happy Oyster",
    category: "Real-Time World Model by Alibaba",
    description: "Describe a world and explore it live, generated frame by frame as you move.",
    price: "$50/HOUR",
    credits: "139 CREDITS/SEC",
    offer: "50% off · first 2 weeks",
    family: "happy",
    docs: "https://docs.reactor.inc/model-api-reference/happy-oyster/overview",
    prompt: "A sunlit meadow with a winding path through ancient ruins",
  },
  "lingbot-world-2": {
    slug: "lingbot-world-2",
    name: "LingBot World 2",
    category: "Action Controlled World Generation",
    description: "High-fidelity environments with real-time interactive output.",
    price: "$12/HOUR",
    credits: "33 CREDITS/SEC",
    family: "world",
    docs: "https://docs.reactor.inc/model-api-reference/lingbot-world-2/overview",
    prompt: "A cinematic path through a rain-soaked futuristic city",
  },
  "sana-streaming": {
    slug: "sana-streaming",
    name: "SANA-Streaming",
    category: "Streaming Video Editing",
    description: "Real-time video editing.",
    price: "$6/HOUR",
    credits: "17 CREDITS/SEC",
    family: "camera",
    docs: "https://docs.reactor.inc/model-api-reference/sana-streaming/overview",
    prompt: "Van Gogh",
    presets: ["Van Gogh", "Pencil Sketch", "Watercolor", "Cowboy Hat", "Royal Crown", "Fox", "Otter", "Neon Cyber", "Claymation"],
  },
  lingbot: {
    slug: "lingbot",
    name: "LingBot",
    category: "Action Controlled World Generation",
    description: "High-fidelity environments with real-time interactive output.",
    price: "$12/HOUR",
    credits: "33 CREDITS/SEC",
    family: "world",
    docs: "https://docs.reactor.inc/model-api-reference/lingbot/overview",
    prompt: "A vast alien landscape with towering crystalline formations",
  },
  "longlive-v2": {
    slug: "longlive-v2",
    name: "LongLive 2",
    category: "Multi-Shot Video Generation",
    description: "Real-time multi-shot video generation with seamless shot changes and hard cuts.",
    price: "$6/HOUR",
    credits: "17 CREDITS/SEC",
    family: "storyboard",
    docs: "https://docs.reactor.inc/model-api-reference/longlive-v2/overview",
    prompt: "A drone reveal of a Martian outpost at sunrise",
  },
  helios: {
    slug: "helios",
    name: "Helios",
    category: "Interactive Video Generation",
    description: "Interactive real-time video generation with infinite streaming.",
    price: "$6/HOUR",
    credits: "17 CREDITS/SEC",
    family: "prompt",
    docs: "https://docs.reactor.inc/model-api-reference/helios/overview",
    prompt: "A lion walking through warm summer rain",
    presets: ["In the Rain", "King of the Jungle"],
  },
};

export const REACTOR_MODEL_SLUGS = Object.keys(REACTOR_MODELS);

export function getReactorModel(slug) {
  return REACTOR_MODELS[slug] || null;
}
